package com.hvac.simulator.topology.validation;

public enum TopologyIssueCode {
    EMPTY_TOPOLOGY,
    DUPLICATE_NODE_ID,
    DUPLICATE_CONNECTION_ID,
    DUPLICATE_CONNECTION_ENDPOINTS,
    UNKNOWN_DEVICE_MODULE,
    UNKNOWN_SOURCE_NODE,
    UNKNOWN_TARGET_NODE,
    UNKNOWN_SOURCE_PORT,
    UNKNOWN_TARGET_PORT,
    SELF_CONNECTION,
    INVALID_DIRECTION,
    INCOMPATIBLE_ENERGY_TYPE,
    INCOMPATIBLE_WATER_SIDE,
    SOURCE_PORT_OCCUPIED,
    TARGET_PORT_OCCUPIED,
    REQUIRED_PORT_UNCONNECTED,
    ISOLATED_NODE
}
